### ISSUE TITLE
Too many active WebGL contexts

### ISSUE THREAD

**Issue by anudit** [latentcat/uvcanvas#1]
![image](https://github.com/latentcat/uvcanvas/assets/12015553/49d8d6a6-676e-4afd-abc1-72a5077b75aa)

Some components don't render correctly in the demo, and a warning shows up in the console after you navigate around a few times.

![image](https://github.com/latentcat/uvcanvas/assets/12015553/d5617500-2552-45a4-9518-ed20bfca8993)

**Comment by ciaochaos** [comment]
Thanks for the feedback! We will solve it later

**Comment by ciaochaos** [comment]
Solved 96532c7b0b787923e9d52cc996aa056a8934cd79
