### ISSUE TITLE
The README file in /core isn't able to render the hero webp image

### ISSUE THREAD

**Issue by JAYKALIA007** [latentcat/uvcanvas#6]
The README file in `/core` is not able to find the hero webp image from `/github` folder. 
It shows `The main branch of uvcanvas does not contain the path core/github/hero.webp`

**Comment by JAYKALIA007** [comment]
I actually went ahead and solved this issue in [this](https://github.com/latentcat/uvcanvas/pull/7) PR.

**Comment by ciaochaos** [comment]
merged
